# 라이브러리 및 데이터 불러오기

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
import matplotlib as mpl

mpl.rcParams["font.family"] = "Malgun Gothic"
mpl.rcParams["axes.unicode_minus"] = False

In [6]:
df_cine = pd.read_csv("C:\\workspace\\sprint_mission16\\data\\cine21_movies.csv")
df_cine.head()

,title,rank,score,daily_aud,total_aud,open_date,link,등급,시간,장르,국가,감독,0,review
0,스파이더맨: 브랜드 뉴 데이,1,7.33,2124592,5910553,2026-07-29,/movie/info/?movie_id=63091,12세이상,144.0,"판타지, 어드벤처, 액션",미국,데스틴 크리튼,7.33,"['하이틴의 겉옷을 벗고 근본으로 돌아간 성장', '큰 힘과 큰 책임이 서로를 따르..."
1,오디세이,2,7.55,1871575,1872877,2026-08-05,/movie/info/?movie_id=62585,15세이상,172.0,"액션, 모험, 드라마",미국,크리스토퍼 놀란,7.55,"['그리스신화는 놀런을 만나길 오랫동안 기다려왔구나', '늘 해오던 걸 가장 잘 할..."
2,사랑의 하츄핑: 고래보석의 전설,3,7.00,407067,433565,2026-08-05,/movie/info/?movie_id=63075,전체,105.0,애니메이션,한국,김수훈,7.00,"['시네마 키드는 어떻게 육성되는가, 이 영화를 보고 자랄 어린이들에게']"
3,호프,4,6.83,219132,4393518,2026-07-15,/movie/info/?movie_id=62480,15세이상,156.0,"액션, 스릴러, SF",한국,나홍진,6.83,"['후진 없는 희망의 트럭', '쾌감의 짝인 공허까지도 납득시킨다', '끌렸다, 즐..."
4,미니언즈 & 몬스터즈,5,6.50,36881,763404,2026-07-15,/movie/info/?movie_id=63032,전체,89.0,애니메이션,미국,피에르 코팽,6.50,"['직업 체험도 좋지만 역시 본업 할 때가 최고', '천사들의 도시로 간 헨리 제임..."

In [7]:
df_kobis = pd.read_csv("C:\\workspace\\sprint_mission16\\data\\kobis_movies.csv")
df_kobis.head()

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,targetDt
0,1,1,0,OLD,20233219,호프,2026-07-15,1057559480,59.5,-1943517630,-64.8,38318463580,103403,-182467,-63.8,3519073,2096,7272,20260727
1,2,2,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,202780900,11.4,-275022600,-57.6,5949070580,21401,-27044,-55.8,584363,774,1856,20260727
2,3,3,0,OLD,20259946,모아나,2026-07-08,145849290,8.2,-200917990,-57.9,9905629670,15049,-19753,-56.8,924284,704,1403,20260727
3,4,4,0,OLD,20259781,토이 스토리 5,2026-06-17,112255100,6.3,-116820500,-51.0,29335606860,11521,-10966,-48.8,2848640,522,854,20260727
4,5,5,1,OLD,20242402,눈동자,2026-06-24,68698000,3.9,-69954370,-50.5,15664161540,6698,-6376,-48.8,1518312,545,885,20260727

# 전처리

## 중복값

In [8]:
df_cine.duplicated().sum()

np.int64(0)

In [9]:
df_kobis.duplicated().sum()

np.int64(0)

## 결측값

In [11]:
print(df_cine.isna().sum().sum())
print(df_kobis.isna().sum().sum())

9
0

In [12]:
df_cine.isna().sum()

title        0
rank         0
score        1
daily_aud    0
total_aud    0
open_date    1
link         0
등급           1
시간           1
장르           1
국가           1
감독           1
0            1
review       1
dtype: int64

In [13]:
df_cine

,title,rank,score,daily_aud,total_aud,open_date,link,등급,시간,장르,국가,감독,0,review
0,스파이더맨: 브랜드 뉴 데이,1,7.33,2124592,5910553,2026-07-29,/movie/info/?movie_id=63091,12세이상,144.0,"판타지, 어드벤처, 액션",미국,데스틴 크리튼,7.33,"['하이틴의 겉옷을 벗고 근본으로 돌아간 성장', '큰 힘과 큰 책임이 서로를 따르..."
1,오디세이,2,7.55,1871575,1872877,2026-08-05,/movie/info/?movie_id=62585,15세이상,172.0,"액션, 모험, 드라마",미국,크리스토퍼 놀란,7.55,"['그리스신화는 놀런을 만나길 오랫동안 기다려왔구나', '늘 해오던 걸 가장 잘 할..."
2,사랑의 하츄핑: 고래보석의 전설,3,7.00,407067,433565,2026-08-05,/movie/info/?movie_id=63075,전체,105.0,애니메이션,한국,김수훈,7.00,"['시네마 키드는 어떻게 육성되는가, 이 영화를 보고 자랄 어린이들에게']"
3,호프,4,6.83,219132,4393518,2026-07-15,/movie/info/?movie_id=62480,15세이상,156.0,"액션, 스릴러, SF",한국,나홍진,6.83,"['후진 없는 희망의 트럭', '쾌감의 짝인 공허까지도 납득시킨다', '끌렸다, 즐..."
4,미니언즈 & 몬스터즈,5,6.50,36881,763404,2026-07-15,/movie/info/?movie_id=63032,전체,89.0,애니메이션,미국,피에르 코팽,6.50,"['직업 체험도 좋지만 역시 본업 할 때가 최고', '천사들의 도시로 간 헨리 제임..."
5,다윗,6,5.00,22913,289372,2026-07-10,/movie/info/?movie_id=63108,전체,109.0,애니메이션,미국,필 커닝햄 브렌트 도스,5.00,['검 대신 악기를 드는 성경 뮤지컬']
6,어떻게 해야 했을까?,7,6.50,22558,49713,2026-07-29,/movie/info/?movie_id=63282,12세이상,101.0,다큐멘터리,일본,후지노 토모아키,6.50,"['‘무엇을 찍었나’로 시작되는 고통. ‘어디서 끊을까’로 확장되는 고뇌', '미해..."
7,토이 스토리 5,8,6.83,19707,2938990,2026-06-17,/movie/info/?movie_id=62799,전체,101.0,애니메이션,미국,앤드류 스탠튼 맥케나 해리스,6.83,"['그 무한한 애정을 어찌 사랑하지 않을 수 있을까', '뭉클하고 눈물겨우나 이젠 ..."
8,모아나,9,5.67,13996,1020487,2026-07-08,/movie/info/?movie_id=62818,전체,115.0,"어드벤처, 액션",미국,토마스 케일,5.67,"['붕어빵이 맛보다 비주얼을 뽐내면', '디즈니 실사영화 논란을 잠재울 충실한 구현..."
9,명탐정 코난: 하이웨이의 타천사,10,NaN,8828,8828,NaN,javascript:;,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
print(df_cine["review"].dtype)
print(type(df_cine.loc[0, "review"]))

str
<class 'str'>

In [23]:
df_cine['score'] = df_cine['score'].fillna(0)
df_cine['open_date'] = df_cine['open_date'].fillna("2026-08-12")
df_cine['link'] = df_cine['link'].replace("javascript:;", "/movie/info/?movie_id=63245")
df_cine['등급'] = df_cine['등급'].fillna("12세이상")
df_cine['시간'] = df_cine['시간'].fillna(109)
df_cine['장르'] = df_cine['장르'].fillna("애니메이션")
df_cine['국가'] = df_cine['국가'].fillna("일본")
df_cine['감독'] = df_cine['감독'].fillna("하스이 타카히로")
df_cine["0"] = df_cine["0"].fillna(6.00)
df_cine["review"] = df_cine["review"].astype(object)
idx = df_cine[df_cine["review"].isna()].index[0]

df_cine.at[idx, "review"] = [
    "스피드에 깔린 미스터리",
    "나도 따라 덜컹거리는 곡선의 박진감. 롤러코스터를 탄 것 같지 않아, 소년?",
    "추리를 접고 직진하여 원점 회귀"
]

In [24]:
df_cine

,title,rank,score,daily_aud,total_aud,open_date,link,등급,시간,장르,국가,감독,0,review
0,스파이더맨: 브랜드 뉴 데이,1,7.33,2124592,5910553,2026-07-29,/movie/info/?movie_id=63091,12세이상,144.0,"판타지, 어드벤처, 액션",미국,데스틴 크리튼,7.33,"['하이틴의 겉옷을 벗고 근본으로 돌아간 성장', '큰 힘과 큰 책임이 서로를 따르..."
1,오디세이,2,7.55,1871575,1872877,2026-08-05,/movie/info/?movie_id=62585,15세이상,172.0,"액션, 모험, 드라마",미국,크리스토퍼 놀란,7.55,"['그리스신화는 놀런을 만나길 오랫동안 기다려왔구나', '늘 해오던 걸 가장 잘 할..."
2,사랑의 하츄핑: 고래보석의 전설,3,7.00,407067,433565,2026-08-05,/movie/info/?movie_id=63075,전체,105.0,애니메이션,한국,김수훈,7.00,"['시네마 키드는 어떻게 육성되는가, 이 영화를 보고 자랄 어린이들에게']"
3,호프,4,6.83,219132,4393518,2026-07-15,/movie/info/?movie_id=62480,15세이상,156.0,"액션, 스릴러, SF",한국,나홍진,6.83,"['후진 없는 희망의 트럭', '쾌감의 짝인 공허까지도 납득시킨다', '끌렸다, 즐..."
4,미니언즈 & 몬스터즈,5,6.50,36881,763404,2026-07-15,/movie/info/?movie_id=63032,전체,89.0,애니메이션,미국,피에르 코팽,6.50,"['직업 체험도 좋지만 역시 본업 할 때가 최고', '천사들의 도시로 간 헨리 제임..."
5,다윗,6,5.00,22913,289372,2026-07-10,/movie/info/?movie_id=63108,전체,109.0,애니메이션,미국,필 커닝햄 브렌트 도스,5.00,['검 대신 악기를 드는 성경 뮤지컬']
6,어떻게 해야 했을까?,7,6.50,22558,49713,2026-07-29,/movie/info/?movie_id=63282,12세이상,101.0,다큐멘터리,일본,후지노 토모아키,6.50,"['‘무엇을 찍었나’로 시작되는 고통. ‘어디서 끊을까’로 확장되는 고뇌', '미해..."
7,토이 스토리 5,8,6.83,19707,2938990,2026-06-17,/movie/info/?movie_id=62799,전체,101.0,애니메이션,미국,앤드류 스탠튼 맥케나 해리스,6.83,"['그 무한한 애정을 어찌 사랑하지 않을 수 있을까', '뭉클하고 눈물겨우나 이젠 ..."
8,모아나,9,5.67,13996,1020487,2026-07-08,/movie/info/?movie_id=62818,전체,115.0,"어드벤처, 액션",미국,토마스 케일,5.67,"['붕어빵이 맛보다 비주얼을 뽐내면', '디즈니 실사영화 논란을 잠재울 충실한 구현..."
9,명탐정 코난: 하이웨이의 타천사,10,0.00,8828,8828,2026-08-12,/movie/info/?movie_id=63245,12세이상,109.0,애니메이션,일본,하스이 타카히로,6.00,"[스피드에 깔린 미스터리, 나도 따라 덜컹거리는 곡선의 박진감. 롤러코스터를 탄 것..."

In [25]:
df_cine["review"] = df_cine["review"].astype(str)

In [26]:
df_cine

,title,rank,score,daily_aud,total_aud,open_date,link,등급,시간,장르,국가,감독,0,review
0,스파이더맨: 브랜드 뉴 데이,1,7.33,2124592,5910553,2026-07-29,/movie/info/?movie_id=63091,12세이상,144.0,"판타지, 어드벤처, 액션",미국,데스틴 크리튼,7.33,"['하이틴의 겉옷을 벗고 근본으로 돌아간 성장', '큰 힘과 큰 책임이 서로를 따르..."
1,오디세이,2,7.55,1871575,1872877,2026-08-05,/movie/info/?movie_id=62585,15세이상,172.0,"액션, 모험, 드라마",미국,크리스토퍼 놀란,7.55,"['그리스신화는 놀런을 만나길 오랫동안 기다려왔구나', '늘 해오던 걸 가장 잘 할..."
2,사랑의 하츄핑: 고래보석의 전설,3,7.00,407067,433565,2026-08-05,/movie/info/?movie_id=63075,전체,105.0,애니메이션,한국,김수훈,7.00,"['시네마 키드는 어떻게 육성되는가, 이 영화를 보고 자랄 어린이들에게']"
3,호프,4,6.83,219132,4393518,2026-07-15,/movie/info/?movie_id=62480,15세이상,156.0,"액션, 스릴러, SF",한국,나홍진,6.83,"['후진 없는 희망의 트럭', '쾌감의 짝인 공허까지도 납득시킨다', '끌렸다, 즐..."
4,미니언즈 & 몬스터즈,5,6.50,36881,763404,2026-07-15,/movie/info/?movie_id=63032,전체,89.0,애니메이션,미국,피에르 코팽,6.50,"['직업 체험도 좋지만 역시 본업 할 때가 최고', '천사들의 도시로 간 헨리 제임..."
5,다윗,6,5.00,22913,289372,2026-07-10,/movie/info/?movie_id=63108,전체,109.0,애니메이션,미국,필 커닝햄 브렌트 도스,5.00,['검 대신 악기를 드는 성경 뮤지컬']
6,어떻게 해야 했을까?,7,6.50,22558,49713,2026-07-29,/movie/info/?movie_id=63282,12세이상,101.0,다큐멘터리,일본,후지노 토모아키,6.50,"['‘무엇을 찍었나’로 시작되는 고통. ‘어디서 끊을까’로 확장되는 고뇌', '미해..."
7,토이 스토리 5,8,6.83,19707,2938990,2026-06-17,/movie/info/?movie_id=62799,전체,101.0,애니메이션,미국,앤드류 스탠튼 맥케나 해리스,6.83,"['그 무한한 애정을 어찌 사랑하지 않을 수 있을까', '뭉클하고 눈물겨우나 이젠 ..."
8,모아나,9,5.67,13996,1020487,2026-07-08,/movie/info/?movie_id=62818,전체,115.0,"어드벤처, 액션",미국,토마스 케일,5.67,"['붕어빵이 맛보다 비주얼을 뽐내면', '디즈니 실사영화 논란을 잠재울 충실한 구현..."
9,명탐정 코난: 하이웨이의 타천사,10,0.00,8828,8828,2026-08-12,/movie/info/?movie_id=63245,12세이상,109.0,애니메이션,일본,하스이 타카히로,6.00,"['스피드에 깔린 미스터리', '나도 따라 덜컹거리는 곡선의 박진감. 롤러코스터를 ..."

In [27]:
df_cine.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      10 non-null     str
 1   rank       10 non-null     int64
 2   score      10 non-null     float64
 3   daily_aud  10 non-null     int64
 4   total_aud  10 non-null     int64
 5   open_date  10 non-null     str
 6   link       10 non-null     str
 7   등급         10 non-null     str
 8   시간         10 non-null     float64
 9   장르         10 non-null     str
 10  국가         10 non-null     str
 11  감독         10 non-null     str
 12  0          10 non-null     float64
 13  review     10 non-null     str
dtypes: float64(3), int64(3), str(8)
memory usage: 1.2 KB

In [28]:
df_kobis

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,targetDt
0,1,1,0,OLD,20233219,호프,2026-07-15,1057559480,59.5,-1943517630,-64.8,38318463580,103403,-182467,-63.8,3519073,2096,7272,20260727
1,2,2,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,202780900,11.4,-275022600,-57.6,5949070580,21401,-27044,-55.8,584363,774,1856,20260727
2,3,3,0,OLD,20259946,모아나,2026-07-08,145849290,8.2,-200917990,-57.9,9905629670,15049,-19753,-56.8,924284,704,1403,20260727
3,4,4,0,OLD,20259781,토이 스토리 5,2026-06-17,112255100,6.3,-116820500,-51.0,29335606860,11521,-10966,-48.8,2848640,522,854,20260727
4,5,5,1,OLD,20242402,눈동자,2026-06-24,68698000,3.9,-69954370,-50.5,15664161540,6698,-6376,-48.8,1518312,545,885,20260727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,6,6,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,19237500,0.4,-25821180,-57.3,7612121820,2193,-2821,-56.3,765485,208,217,20260810
146,7,7,3,OLD,20259781,토이 스토리 5,2026-06-17,10804150,0.2,-7973700,-42.5,30219382390,1112,-795,-41.7,2940488,109,112,20260810
147,8,8,-3,OLD,20262902,다윗,2026-07-10,9168150,0.2,-69105900,-88.3,2816467330,958,-7384,-88.5,290308,65,69,20260810
148,9,9,3,OLD,20259946,모아나,2026-07-08,7290500,0.1,748300,11.4,10828554930,826,149,22.0,1021761,67,70,20260810
149,10,10,5,OLD,20263530,마티 슈프림,2026-07-01,2896500,0.1,-2994350,-50.8,1426494680,290,-107,-27.0,131844,18,18,20260810

In [29]:
df_kobis.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   rnum           150 non-null    int64
 1   rank           150 non-null    int64
 2   rankInten      150 non-null    int64
 3   rankOldAndNew  150 non-null    str
 4   movieCd        150 non-null    int64
 5   movieNm        150 non-null    str
 6   openDt         150 non-null    str
 7   salesAmt       150 non-null    int64
 8   salesShare     150 non-null    float64
 9   salesInten     150 non-null    int64
 10  salesChange    150 non-null    float64
 11  salesAcc       150 non-null    int64
 12  audiCnt        150 non-null    int64
 13  audiInten      150 non-null    int64
 14  audiChange     150 non-null    float64
 15  audiAcc        150 non-null    int64
 16  scrnCnt        150 non-null    int64
 17  showCnt        150 non-null    int64
 18  targetDt       150 non-null    int64
dtypes: float64(3), int64(13), str(3)
memory usage: 22.4 KB