In [5]:
from dotenv import load_dotenv

import os
import requests
import pandas as pd

load_dotenv()

api_key = os.getenv("API_KEY")

In [6]:
api_key is not None

True

In [7]:
url = "https://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json"

df_list = []

for i in range(20260727, 20260732):

    params = {
        "key": api_key,
        "targetDt": str(i)
    }

    response = requests.get(url, params=params)

    print(i, response.status_code)

    data = response.json()

    movie_list = data["boxOfficeResult"]["dailyBoxOfficeList"]

    df_temp = pd.DataFrame(movie_list)

    # 조회 날짜 추가
    df_temp["targetDt"] = str(i)

    # 날짜별 DataFrame을 리스트에 저장
    df_list.append(df_temp)


# 모든 날짜 데이터 합치기
df = pd.concat(df_list, ignore_index=True)

df.head()

20260727 200
20260728 200
20260729 200
20260730 200
20260731 200

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,targetDt
0,1,1,0,OLD,20233219,호프,2026-07-15,1057559480,59.5,-1943517630,-64.8,38318463580,103403,-182467,-63.8,3519073,2096,7272,20260727
1,2,2,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,202780900,11.4,-275022600,-57.6,5949070580,21401,-27044,-55.8,584363,774,1856,20260727
2,3,3,0,OLD,20259946,모아나,2026-07-08,145849290,8.2,-200917990,-57.9,9905629670,15049,-19753,-56.8,924284,704,1403,20260727
3,4,4,0,OLD,20259781,토이 스토리 5,2026-06-17,112255100,6.3,-116820500,-51,29335606860,11521,-10966,-48.8,2848640,522,854,20260727
4,5,5,1,OLD,20242402,눈동자,2026-06-24,68698000,3.9,-69954370,-50.5,15664161540,6698,-6376,-48.8,1518312,545,885,20260727

In [8]:
url = "https://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json"

df_list1 = []

for i in range(20260801, 20260811):

    params = {
        "key": api_key,
        "targetDt": str(i)
    }

    response1 = requests.get(url, params=params)

    print(i, response1.status_code)

    data1 = response1.json()

    movie_list1 = data1["boxOfficeResult"]["dailyBoxOfficeList"]

    df_temp1 = pd.DataFrame(movie_list1)

    # 조회 날짜 추가
    df_temp1["targetDt"] = str(i)

    # 날짜별 DataFrame을 리스트에 저장
    df_list1.append(df_temp1)


# 모든 날짜 데이터 합치기
df1 = pd.concat(df_list1, ignore_index=True)

df1.head()

20260801 200
20260802 200
20260803 200
20260804 200
20260805 200
20260806 200
20260807 200
20260808 200
20260809 200
20260810 200

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,targetDt
0,1,1,0,OLD,20262770,스파이더맨: 브랜드 뉴 데이,2026-07-29,9697312810,80.9,3900487860,67.3,27082628950,901580,375250,71.3,2561990,2409,10152,20260801
1,2,2,0,OLD,20233219,호프,2026-07-15,1403300900,11.7,567632100,67.9,43077979680,136417,54921,67.4,3992655,957,2724,20260801
2,3,3,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,211440510,1.8,21218580,11.2,6935364100,22173,2131,10.6,690912,715,1091,20260801
3,4,4,0,OLD,20259946,모아나,2026-07-08,124133850,1.0,11528250,10.2,10502690130,12729,1099,9.4,987186,465,626,20260801
4,5,5,0,NEW,20262381,사랑의 하츄핑: 고래보석의 전설,2026-08-05,127985600,1.1,127985600,100,181687600,10681,10681,100,16189,76,91,20260801

In [9]:
df_total = pd.concat([df, df1], ignore_index=True)
df_total

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,targetDt
0,1,1,0,OLD,20233219,호프,2026-07-15,1057559480,59.5,-1943517630,-64.8,38318463580,103403,-182467,-63.8,3519073,2096,7272,20260727
1,2,2,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,202780900,11.4,-275022600,-57.6,5949070580,21401,-27044,-55.8,584363,774,1856,20260727
2,3,3,0,OLD,20259946,모아나,2026-07-08,145849290,8.2,-200917990,-57.9,9905629670,15049,-19753,-56.8,924284,704,1403,20260727
3,4,4,0,OLD,20259781,토이 스토리 5,2026-06-17,112255100,6.3,-116820500,-51,29335606860,11521,-10966,-48.8,2848640,522,854,20260727
4,5,5,1,OLD,20242402,눈동자,2026-06-24,68698000,3.9,-69954370,-50.5,15664161540,6698,-6376,-48.8,1518312,545,885,20260727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,6,6,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,19237500,0.4,-25821180,-57.3,7612121820,2193,-2821,-56.3,765485,208,217,20260810
146,7,7,3,OLD,20259781,토이 스토리 5,2026-06-17,10804150,0.2,-7973700,-42.5,30219382390,1112,-795,-41.7,2940488,109,112,20260810
147,8,8,-3,OLD,20262902,다윗,2026-07-10,9168150,0.2,-69105900,-88.3,2816467330,958,-7384,-88.5,290308,65,69,20260810
148,9,9,3,OLD,20259946,모아나,2026-07-08,7290500,0.1,748300,11.4,10828554930,826,149,22,1021761,67,70,20260810
149,10,10,5,OLD,20263530,마티 슈프림,2026-07-01,2896500,0.1,-2994350,-50.8,1426494680,290,-107,-27,131844,18,18,20260810

In [10]:
df_total

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,targetDt
0,1,1,0,OLD,20233219,호프,2026-07-15,1057559480,59.5,-1943517630,-64.8,38318463580,103403,-182467,-63.8,3519073,2096,7272,20260727
1,2,2,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,202780900,11.4,-275022600,-57.6,5949070580,21401,-27044,-55.8,584363,774,1856,20260727
2,3,3,0,OLD,20259946,모아나,2026-07-08,145849290,8.2,-200917990,-57.9,9905629670,15049,-19753,-56.8,924284,704,1403,20260727
3,4,4,0,OLD,20259781,토이 스토리 5,2026-06-17,112255100,6.3,-116820500,-51,29335606860,11521,-10966,-48.8,2848640,522,854,20260727
4,5,5,1,OLD,20242402,눈동자,2026-06-24,68698000,3.9,-69954370,-50.5,15664161540,6698,-6376,-48.8,1518312,545,885,20260727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,6,6,0,OLD,20261784,미니언즈 & 몬스터즈,2026-07-15,19237500,0.4,-25821180,-57.3,7612121820,2193,-2821,-56.3,765485,208,217,20260810
146,7,7,3,OLD,20259781,토이 스토리 5,2026-06-17,10804150,0.2,-7973700,-42.5,30219382390,1112,-795,-41.7,2940488,109,112,20260810
147,8,8,-3,OLD,20262902,다윗,2026-07-10,9168150,0.2,-69105900,-88.3,2816467330,958,-7384,-88.5,290308,65,69,20260810
148,9,9,3,OLD,20259946,모아나,2026-07-08,7290500,0.1,748300,11.4,10828554930,826,149,22,1021761,67,70,20260810
149,10,10,5,OLD,20263530,마티 슈프림,2026-07-01,2896500,0.1,-2994350,-50.8,1426494680,290,-107,-27,131844,18,18,20260810

In [11]:
df_total.to_csv(
    "../data/kobis_movies.csv",
    index=False,
    encoding="utf-8-sig"
)